services:
  - type: web
    name: tts-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        value: "593348183512-bi8t063tk73uesvqd6j643btukr8uia4.apps.googleusercontent.com"
      - key: PING_URL
        value: "https://ech-efmm.onrender.com/health"

